# Generated by Django 3.2.8 on 2021-10-20 17:16

import User.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', User.managers.UserManager()),
            ],
        ),
    ]
